# Generated by Django 5.2 on 2025-05-13 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_seen_guide', models.BooleanField(default=False)),
                ('avatar', models.CharField(default='avatar0.png', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('do_not_disturb', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('prefers_dark_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'todo_userprofile',
            },
        ),
    ]
